### ISSUE TITLE
Running CNN model in ELL

### ISSUE THREAD

**Issue by Tryljs** [Microsoft/ELL#103]
Dear Team,
Does ELL support running CNN models from darknet or CNTK?

**Comment by lovettchris** [comment]
Yes it does, see the tutorial on [importing models ](https://microsoft.github.io/ELL/tutorials/Importing-models/) for examples.

**Comment by Tryljs** [comment]
Thank you!  
In the ELL, is the darknet model running  with a ELL frame or a darknet frame ?  And  what's the use of the codes in the neural file?

**Comment by lovettchris** [comment]
If by "frame" you mean the input image format, the ELL model is expecting the same format RGB that darknet is expecting (not BGR like CNTK and opencv).  This is why our demoHelper.py makes the BGR to RGB conversion optional, so in the darknet case you request pass bgr=false.  This is mentioned in the tutorial at the bottom:

> Note: Using a converted Darknet model from pjreddie will require OpenCV input reordered from BGR to RGB. tutorial_helpers.py and tutorialHelpers.h provide helper functions for Python and C++, respectively, that take an argument to reorder the input image from BGR to RGB.

Looking at the tutorial_helpers prepare_image_for_model the argument is named reorder_to_rgb, so in the darknet case you set this to true.

But in [demoHelper.py](https://github.com/Microsoft/ELL/blob/master/tools/utilities/pythonlibs/demoHelper.py) it is called "bgr" and is an option to DemoHelper, and so in the darknet case you set that to false.

**Comment by Tryljs** [comment]
If i want to use c++ to call the darknet model, does the ELL can  provide some function interfaces to implement it?

**Comment by kernhanda** [comment]
Yes, if you look at https://microsoft.github.io/ELL/tutorials/Getting-started-with-image-classification-in-cpp/, you can see that ELL creates a function called `model_Predict`, where `model` can be replaced by a name of your choice.

**Comment by Tryljs** [comment]
Thank you!
