### ISSUE TITLE
Fix proper processor detection for popular processor families and models

### ISSUE THREAD

**Issue by IvanFarkas** [Microsoft/ELL#105]
Please fix proper processor detection for popular processor families and models in CMake\OpenBLASSetup.cmake.
My XPS 15 9560 has Intel Core i7-7700HQ (Family 6 Model 158 Stepping 9)
Could you please add the code section to the model detection section between line 88-106?
While you are at it fix typo as well (**_Kobylake_** -> **_Kabylake_** and **_Koby Lake_** -> **_Kaby Lake_**)
Thx in advance.

```cmake
elseif (processor_model EQUAL 158)
    set(processor_generation "haswell") # technically this is Kaby Lake, but it is compatible with haswell.

```

**Comment by lovettchris** [comment]
Thanks, fix is on the way.
