### ISSUE TITLE
darknet to ell

### ISSUE THREAD

**Issue by Tryljs** [Microsoft/ELL#113]
Dear team
Running the darknetDemo.py script then the darknet model would be save as 'darknetReference.map'. And I found the model builder functions in 'ModelInterface.h' file, but I coundn't find the 'darknetReference.map' to ELL model function. I tried to use 'ELL_Model(darknetReference.map) ' function and 'ELL_Map(darknetReference.map)' function to realize 'darknetReference.map' to ELL model, but failed. Does the ELL offer the function to make 'darknetReference.map' to the ELL model ?

**Comment by lovettchris** [comment]
If you follow the [Importing Models ](https://microsoft.github.io/ELL/tutorials/Importing-models/) tutorial it will show you how to use wrap.py to generate a darknet model from the darknet .cfg and .weights files.  The resulting *.ell file can then be loaded into python using ELL.ELL_Map.  But it is better if you compile the .ell file to code as discussed in [Step 3 of the Getting started tutorial](https://microsoft.github.io/ELL/tutorials/Getting-started-with-image-classification-on-the-Raspberry-Pi/).
