### ISSUE TITLE
Does wrap.py can make the darknet to Cortex-A9 platforms 

### ISSUE THREAD

**Issue by Tryljs** [Microsoft/ELL#120]
I want to run ELL on Cortex-A9, but wrap.py just support target platforms are pi3, aarch64 and host, none of them are ARMv7 framework. And I find the cross compiling of 'arm-poky-linux-gnueabi-gcc' coundn't to compile ELL, because the std of 'arm-poky-linux-gnueabi-gcc' is not supported. How can I do for ELL to make it run on Cortex-A9?

**Comment by lovettchris** [comment]
Yes, underneath wrap.py is a tool called compile (which you will find in your build/bin folder after building ELL).  If you run wrap.py on a model with the "--verbose" argument you will see what command line arguments it is passing to compile.  You can then modify those arguments to specify the Cortex-A9 cpu as follows and the special target of "custom" meaning, you are providing cpu, triple, and dataLayout.  
```
D:/git/ELL/ELL/build/bin/release/compile -imap mnist.ell -cfn Predict -cmn mnist --target custom -od . --fuseLinearOps True --blas false --optimize true --triple armv7ve-linux-gnueabihf --cpu cortex-a9 --numBits 32 --dataLayout e-m:e-p:32:32-i64:64-v128:64:128-a:0:32-n32-S64  --objectCode --features "+neon,-soft-float,+virtualization" --header
```
Note: this is a custom cortex-a7 chip running a 32bit Linux OS.  If your OS is 64 bit you will need --numBits 64 and the dataLayout of "e-m:e-i64:64-i128:128-n32:64-S128"

See [LLVM data-layout](https://llvm.org/docs/LangRef.html#data-layout).
