### ISSUE TITLE
Erro:Building the ELL on Ubuntu Linux

### ISSUE THREAD

**Issue by Tryljs** [Microsoft/ELL#124]
Building message:
......
[ 55%] Building CXX object libraries/common/CMakeFiles/common.dir/src/LoadModel.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
libraries/common/CMakeFiles/common.dir/build.make:158: recipe for target 'libraries/common/CMakeFiles/common.dir/src/LoadModel.cpp.o' failed
make[2]: *** [libraries/common/CMakeFiles/common.dir/src/LoadModel.cpp.o] Error 4
CMakeFiles/Makefile2:216: recipe for target 'libraries/common/CMakeFiles/common.dir/all' failed
make[1]: *** [libraries/common/CMakeFiles/common.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kernhanda** [comment]
This looks to be a fault with the compiler. It should never be killed when compiling a file. Please file a bug report for your compiler and/or upgrade your compiler.

For the sake of curiousity, what's the version of your compiler?

**Comment by Tryljs** [comment]
My compiler's version is 5.4.0.20160609

**Comment by Tryljs** [comment]
I upgrade my compiler version with 6.3.0. But it doesn't work.

**Comment by kernhanda** [comment]
Does it result in the same error? Can you please run the following (feel free to adjust the `cmake` commands if you were doing something different, but please call it out) in the ELL repository

```shell
git clean -fdx
mkdir build
cd build
cmake ..
cmake --build .
```
and share the output?

**Comment by Tryljs** [comment]
This problem had been solved.

**Comment by kernhanda** [comment]
Thanks. What was the problem?

**Comment by Tryljs** [comment]
Lack of caching

**Comment by kernhanda** [comment]
Thanks!

**Comment by JayjieL** [comment]
so how to solve this problem....
