### ISSUE TITLE
Trouble: complier darknet project

### ISSUE THREAD

**Issue by Tryljs** [Microsoft/ELL#125]
I used wrap.py script to process the darknet model, and then  I got a darknet.obj file. When I used it to complier a demo, but failed. Error message as following:

darknet.obj : error LNK2019: in function 'darknet_Predict', undefined reference to 'darknet_InputCallback';
darknet.obj : error LNK2019: in function 'darknet_Predict', undefined reference to 'cblas_sgemm';
darknet.obj : error LNK2019: in function 'darknet_Predict', undefined reference to 'darknet_OutputCallback';

**Comment by Tryljs** [comment]
In the predict function, I found its parameters are "double", "float*", how to input my picture to predict the result?

**Comment by lisaong** [comment]
This is now fixed with release v2.1.5
