### ISSUE TITLE
Getting WrapException: <class 'buildtools.EllBuildToolsRunException'>

### ISSUE THREAD

**Issue by HaRo87** [Microsoft/ELL#131]
Hey folks,
after following the [installation steps for Ubuntu](https://github.com/Microsoft/ELL/blob/master/INSTALL-Ubuntu.md) on a fresh Ubuntu 16.04 image and pulling the latest version of ELL, I've started to follow [this tutorial](https://microsoft.github.io/ELL/tutorials/Getting-started-with-image-classification-on-the-Raspberry-Pi/) until the point where I need to call wrap.py:
`python <ELL-root>/tools/wrap/wrap.py model.ell -lang python -target host`

Which produces the following error:
`WrapException: <class 'buildtools.EllBuildToolsRunException'>:`

after showing `compiling model...`.

I used pdg to debug and it seems like the bad stuff happens on [line 187](https://github.com/Microsoft/ELL/blob/master/tools/wrap/wrap.py#L187) in `wrap.py`. But I was not able to figure out the root cause. I am still learning Python which might be the reason for not being able to figure out the problem.

Any help would be much appreciated.

Thanks and cheers,
Robert

**Comment by lisaong** [comment]
I've seen this exception when I've accidentally run python 2.7 instead of python 3.6.  Type "which python" in your command line, or try:

`python3 <ELL-root>/tools/wrap/wrap.py model.ell -lang python -target host`
