### ISSUE TITLE
Error configure python interface

### ISSUE THREAD

**Issue by braca51e** [Microsoft/ELL#134]
Hi I'm trying to build with ubuntu 16.04 and I keep getting this error:
CMake Error at interfaces/python/CMakeLists.txt:65 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:_ELL_python>

  Target "_ELL_python" is not an executable or library.

Thanks for your help.

**Comment by braca51e** [comment]
Found the problem!
Wrong swig version.

**Comment by kernhanda** [comment]
Thanks for letting us know! Closing this issue.
