### ISSUE TITLE
Compilation instructions for rpi

### ISSUE THREAD

**Issue by braca51e** [Microsoft/ELL#135]
I'm trying to compile the library and run it in rpi. I haven't found specific instrutntions. Thanks for your help!

**Comment by braca51e** [comment]
Already found docs!!!

**Comment by kernhanda** [comment]
Did the docs provide the instructions you were looking for?

**Comment by braca51e** [comment]
Yes they did, Thanks!
Bus I was confused because the name says Getting started with image classification on Raspberry Pi and the first steps tell you how to run on a Computer and that was not indicated in the beginning. I had to read all step until I realized that what I actually needed started until step 5!

**Comment by kernhanda** [comment]
Thanks for the feedback!
