### ISSUE TITLE
modelhelpers.py missing from <root>\tools\utilities\pythonlibs\

### ISSUE THREAD

**Issue by CalderaSrv** [Microsoft/ELL#140]
Hello,

When running the Repurposing-a-pretrained-image-classifier tutorial in 2.3.2, I get an error when running the training image assembler:

python <ELL-root>/tools/utilities/datasetFromImages/datasetFromImages.py --imageSize 64x64 --outputDataset fruit_train.gsdf --folder data/fruit/train

Error:
Traceback (most recent call last):
  File "S:/ELL-2.3.2/tools/utilities/datasetFromImages/datasetFromImages.py", line 20, in <module>
    import modelHelpers
ModuleNotFoundError: No module named 'modelHelpers'

I was able to resolve by copying modelhelpers.py from a earlier release into \pythonlibs\, so maybe the simple fix is just to add the missing file in the repository.

Thanks,

**Comment by kernhanda** [comment]
Thanks for letting us know. This file was accidentally deleted. It will be restored in the next release.
