### ISSUE TITLE
retargetTrainer.exe crashing

### ISSUE THREAD

**Issue by CalderaSrv** [Microsoft/ELL#141]
Hello,

retargetTrainer.exe is crashing in the new 2.3.2 release. 

My system:
Windows10, i7

Example command:
S:\ELL-2.3.2\build\bin\release\retargetTrainer --maxEpochs 1000 --multiClass true --refineIterations 1 --inputModelFilename pretrained.ell --targetPortElements 1448.output --inputDataFilename MyTrain.gsdf --outputModelFilename model.ell

Output:
Redirected output for port elements 1448.output from model
Then it crashes:
![image](https://user-images.githubusercontent.com/26381789/39078990-01c7472a-44d8-11e8-897b-a2039ee6de3c.png)

I have tested on these models and observe the same behavior:
dsf_I64x64x3CCMCCMCCMCMCMC1AS.ell, --targetPortElements 1448.output
Candlenut.ell --targetPortElements 1891.output
PandanFlower.ell --targetPortElements 3295.output

I am able to run without errors if I swap in my retargetTrainer.exe from 2.3.0 into my 2.3.2 \ELL-2.3.2\build\bin\Release\ folder

**Comment by lovettchris** [comment]
I've confirmed this crash, we are investigating...

**Comment by lovettchris** [comment]
Found the problem, the DataLoader.tcc uses old prototype for callback functions.  The callbacks now take a void* context parameter, the fix will be included in next update.

**Comment by kernhanda** [comment]
Resolved with release [v2.3.5](https://github.com/Microsoft/ELL/tree/v2.3.5).
