### ISSUE TITLE
Compilation error file WinogradConvolution.cpp

### ISSUE THREAD

**Issue by braca51e** [Microsoft/ELL#157]
I'm trying to compile ELL following the steps in the read me and keep getting this error even after clean install:

dsp/src/WinogradConvolution.cpp:1364:25: error: array must be initialized with a brace-enclosed initializer
             WindowArray X;

Any ideas or directions on how to compile the latest version?

**Comment by jesuspicazo** [comment]
I'm facing the same issue too. Please, any help?

**Comment by cjacobs** [comment]
Thanks for the report! I'll take a look.

**Comment by langongjin** [comment]
I have the same issue too, so how is it going right now

**Comment by jesuspicazo** [comment]
Please, are there any updates?

**Comment by kernhanda** [comment]
Resolved with release [v2.3.5](https://github.com/Microsoft/ELL/tree/v2.3.5)
