### ISSUE TITLE
Instructions to build

### ISSUE THREAD

**Issue by VedAustin** [Microsoft/ELL#16]
I have a clarification to make:
Looking at the instructions here:
https://github.com/Microsoft/ELL/blob/master/INSTALL-Windows.md

After this line `NuGet will download the prerequisites into the ELL/external directory.`
I have to run:
`cmake -G "Visual Studio 15 2017 Win64" -DPROCESSOR_HINT=haswell ..`

Do I need to change my directory to `external` because if I stay in `ELL`, and run the above command then the file `CMakeLists.txt` file will not be found.

Also when building the ELL in the `build` folder:
`cmake -G "Visual Studio 14 2015 Win64" -DPROCESSOR_HINT=haswell ..`

However since I have Visual Studio 2017 installed, can we also use this instead:
`cmake -G "Visual Studio 15 2017 Win64" -DPROCESSOR_HINT=haswell ..`

**Comment by clovett** [comment]
You are right we are missing these steps in the readme:
```
mkdir build
cd build
```
Then run cmake.  We do have the VS 2017 command line in the readme. But I'll get the above added.

**Comment by eulesv** [comment]
I'll piggy back on this one... right at the end of the tutorial, it makes a reference to a build script (compile_darknetReference.cmd)... where is this script located?

**Comment by VedAustin** [comment]
I found this under `build\tutorials\vision\gettingStarted`

But I also found a `tutorial` folder under the root `ELL`. So I am a bit confused about two `tutorials` folder being present.

**Comment by eulesv** [comment]
The one at the root is the original folder, the one under build is a copy created during build; I'm following the contentes of a compiling.md file but the tutorial says there is a build script, i think this file is missing on the repo

**Comment by eulesv** [comment]
Nevermind... I just realized those files where added after I originally clone the repo, I just did fetch/pull :)
