### ISSUE TITLE
Not able to port the ELL to Raspberry PI W Zero.

### ISSUE THREAD

**Issue by Raulpb49** [Microsoft/ELL#161]
I tried installing it on raspberry Pi . I followed all the instructions(till SWIG(excluding)
Below are the steps I  skipped as I think they are mentioned optional.

1.curl -O --location http://prdownloads.sourceforge.net/swig/swig-3.0.12.tar.gz
tar zxvf swig-3.0.12.tar.gz && cd swig-3.0.12
./configure --without-pcre && make && sudo make install
Using ELL in Python

2.conda create -n py36 numpy python=3.6
Next, activate the environment you just created by typing

3.source activate py36

4.conda install -c conda-forge opencv -y

after I build , >>

my build is not getting past 37%
After below lines ,it seems to stuck forever.

/usr/include/c++/6/bits/stl_vector.h: In member function 'void std::vector<_Tp, _Alloc>::assign(_InputIterator, _InputIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const double*, std::vector<double> >; <template-parameter-2-2> = void; _Tp = double; _Alloc = std::allocator<double>]':
/usr/include/c++/6/bits/stl_vector.h:508:9: note: parameter passing for argument of type '__gnu_cxx::__normal_iterator<const double*, std::vector<double> >' will change in GCC 7.1
         assign(_InputIterator __first, _InputIterator __last)
         ^~~~~~
/usr/include/c++/6/bits/stl_vector.h:508:9: note: parameter passing for argument of type '__gnu_cxx::__normal_iterator<const double*, std::vector<double> >' will change in GCC 7.1
/usr/include/c++/6/bits/stl_vector.h:509:11: note: parameter passing for argument of type '__gnu_cxx::__normal_iterator<const double*, std::vector<double> >' will change in GCC 7.1
         { _M_assign_dispatch(__first, __last, __false_type()); }
           ^~~~~~~~~~~~~~~~~~
**/usr/include/c++/6/bits/stl_vector.h:509:11: note: parameter passing for argument of type '__gnu_cxx::__normal_iterator<const double*, std::vector<double> >' will change in GCC 7.1
/usr/include/c++/6/bits/stl_vector.h:509:11: note: parameter passing for argument of type '__gnu_cxx::__normal_iterator<const double*, std::vector<double> >' will change in GCC 7.1**

What have I missed?
Is there a binary which I can refer instead of building from the sources?

Many thanks in advance !
Rgds,
Rp

**Comment by clovett** [comment]
We don't normally build ELL itself on raspberry Pi zero, because ELL is actually a cross-compiler, you can build "ELL Models to run on raspberry pi" by using "ELL on your PC".   but if you really do want to compile ELL on the pi0, you may need to upgrade your GCC compiler to 6.4.  It could also be the compiler needs some [swap space](http://raspberrypimaker.com/adding-swap-to-the-raspberrypi/).

**Comment by Raulpb49** [comment]
Great ! Thanks for the information.
Rgds
Rp

**Comment by kernhanda** [comment]
Resolved with release [v2.3.5](https://github.com/Microsoft/ELL/tree/v2.3.5)
