### ISSUE TITLE
Cannot download the raw zip model files. 

### ISSUE THREAD

**Issue by riple** [Microsoft/ELL#163]
All the model files in .zip format cannot be downloaded. All I got from the RAW link on the .zip file page is a 133Byte description of the file property.

I even tried to download the whole repository in a zip package. (I even tried to git clone the repository to my computer). The content of the particular *.zip file is the same 133Byte description.

**Comment by CalderaSrv** [comment]
I also had problems in the past week.  Specifically with the "ELL featurizer model file" and "ELL classifier model file" from the "Getting started with audio keyword classification" tutorial.  http links and curl commands download a 1kb zip file with no usable content.

**Comment by riple** [comment]
> desktop:~/work/ell/ELL-models/models/ILSVRC2012/d_I224x224x3CMCMCMCMCMCMC1AS$ git lfs fetch
fetch: Fetching reference refs/heads/master
batch response: This repository is over its data quota. Purchase more data packs to restore access.                                           
batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/Microsoft/ELL-models.git/info/lfs'

**Comment by lovettchris** [comment]
Yep, sorry about that, we ran up against our bandwidth quota, we are working on a fix, apologies for the inconvenience.

**Comment by lovettchris** [comment]
This is fixed now.
