### ISSUE TITLE
python kernel died when invoking ELL on PC, without error information...

### ISSUE THREAD

**Issue by mingyangSunshine** [Microsoft/ELL#167]
I have installed ELL on my PC(win10 x64) as described in the page: [https://github.com/Microsoft/ELL/blob/master/INSTALL-Windows.md](https://github.com/Microsoft/ELL/blob/master/INSTALL-Windows.md), 
and I am following the steps in the instruction "Getting started with image classification on Raspberry Pi", Invoke the model on your computer part. 
[https://microsoft.github.io/ELL/tutorials/Getting-started-with-image-classification-on-the-Raspberry-Pi/](https://microsoft.github.io/ELL/tutorials/Getting-started-with-image-classification-on-the-Raspberry-Pi/)

When I tried to run the python script "call_model.py" in anaconda environment py36, the python kernel died without printing any error messages. I found that the command "predictions = model.predict(input_data)" caused the problem.
the script is as follows:
```python
import cv2
import numpy as np
import tutorial_helpers as helpers
import model

input_shape = model.get_default_input_shape()
output_shape = model.get_default_output_shape()

print("Model input shape: [{0.rows}, {0.columns}, {0.channels}]".format(
    input_shape))
print("Model output shape: [{0.rows}, {0.columns}, {0.channels}]".format(
    output_shape))

sample_image = cv2.imread("coffeemug.jpg")
print("image read")
input_data = helpers.prepare_image_for_model(sample_image, input_shape.columns, input_shape.rows)
predictions = model.predict(input_data)


prediction_index = int(np.argmax(predictions))
print("Category index: {}".format(prediction_index))
print("Confidence: {}".format(predictions[prediction_index]))
```

the output is:
```python
Model input shape: [224, 224, 3]
Model output shape: [1, 1, 1000]
image read
```
I have tried jupyter notebook, spyder, and cmd, then the kernel all died.
I do not know where is the problem...anyone who can help me?

**Comment by mingyangSunshine** [comment]
I have tried the same process on My desktop PC, and it ran successfully. But it kept crashing on my laptop.

**Comment by lovettchris** [comment]
This might indicate a problem with the "OpenBlas" version you are using on your laptop, perhaps it doesn't properly match the CPU you have there.  Can you attach the output of "dxdiag" so we can check your laptop CPU model ?

**Comment by mingyangSunshine** [comment]
Thanks, @lovettchris !
dxdiag output is:
<img width="546" alt="untitled" src="https://user-images.githubusercontent.com/16488037/43363458-de70899a-9337-11e8-8df4-541109c11f50.png">

I found that if I copy the model compiled on my desktop PC to the laptop, it ran correctly. But the model complied on my laptop doesn't work on any computer.

laptop software version:

- Mircosoft Visual Studio 2017 community version15.7.5

- OpenBLASLibs.0.2.19.3

- anaconda environment: python 3.6.6

- cmake 3.12.0

**Comment by clovett** [comment]
Interesting data, thanks.  This is a skylake processor which we haven't tested well.  Can you print your PROCESSOR_IDENTIFIER number, I suspect it is model 42 which we've mapped to the "sandybridge" version of OpenBLAS.  So to setup your PATH correctly you would do this:

```
set PATH=%PATH%;D:\git\ELL\ELL\external\OpenBLASLibs.0.2.19.3\build\native\x64\sandybridge\bin
```

**Comment by clovett** [comment]
Very interesting that a model copied from your desktop runs fine.  This indicates it is not an OpenBLAS problem, but instead a code generation problem which is really odd, we haven't seen that with Intel CPU's, normally our LLVM backend is very reliable about generating good code...  So can you also print PROCESSOR_IDENTIFIER environment variable from your desktop PC ? And does the desktop also have OpenBLAS setup ?  I wonder if PC was build a non-openBLAS version for some reason...
