### ISSUE TITLE
ELL vs. Azure IoT Edge

### ISSUE THREAD

**Issue by bhakthil** [Microsoft/ELL#177]
Hi ELL Team,
I would like to get some feedback from ELL team on the differences between ELL and Azure IoT Edge. Azure IoT edge is capable of running AI workloads on small devices like RPi. what are the reasons that one would take a painful route of building/compiling models when the models can be trained on Azure and transferred and executed in docker containers on RPi. I am planning to do a talk on ELL at NY code camp and I would like to know some use cases that ELL can be advantages over Azure IoT edge.

BL

**Comment by clovett** [comment]
First Azure IoT Edge is a product, whereas ELL is research.  We are researching how to maximize the speed of a model that runs on tiny hardware, all the way down to Cortex-M4 class chips and therefore also how to minimize the size of these models and how to fit them into memory constrained devices.  As we make progress on this front we've love to see our ideas get incorporated into products, including Azure IoT Edge.  The Azure Iot Dev Kit with the MXCHIP board is a great example.  We have ELL compiled Audio Keyword Spotting models running on this device.  I don't believe Azure IoT Edge can remotely provision these devices yet, but hey, that would be great too.  Combined this with Azure Sphere and provide a full ALM story around managing your models and sending as much intelligence to your edge devices as possible.  We envision some day the cloud being able to intelligently decide which models to run in the cloud and which to run on the device, and even better if the device models could be automatically derived from the big models and performance tuned to run on the devices.  Imagine something like the Ring Doorbell, where the cloud can send some intelligence to the device, the device might then tell the cloud "I think a person is standing at the front door" and the cloud then gets involved and verifies this with a bigger more reliable model.  This kind of hybrid approach takes the best of both worlds with cloud and intelligent device working together to provide the most cost effective and intelligent solution for customers.  So ELL is researching all this and providing open source to help facilitate community involvement as we push towards this vision.
