### ISSUE TITLE
cmake fails in Centos 7.4

### ISSUE THREAD

**Issue by Manojmks** [Microsoft/ELL#178]
[root@abc build]# cmake ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found LIBBFD: /usr/lib64/libbfd.so
-- Target architectures: x86_64
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Found CURL: /usr/lib64/libcurl.so (found version "7.29.0")
-- Found DL: /usr/lib64/libdl.so
-- Found M: /usr/lib64/libm.so
-- Found LibElf: /usr/lib64/libelf.so
-- Could NOT find ElfUtils (missing:  LIBDW_LIBRARY LIBDW_INCLUDE_DIR)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBDW_LIBRARY (ADVANCED)
    linked by target "kcov" in directory /root/kcov-master/src

-- Configuring incomplete, errors occurred!
See also "/root/kcov-master/build/CMakeFiles/CMakeOutput.log".
See also "/root/kcov-master/build/CMakeFiles/CMakeError.log".
[root@abc build]#
[root@abc build]#
[root@abc build]# rpm -qa | grep -i ElfUtils
elfutils-libelf-0.170-4.el7.x86_64
elfutils-libelf-0.170-4.el7.i686
elfutils-default-yama-scope-0.170-4.el7.noarch
elfutils-libs-0.170-4.el7.i686
devtoolset-7-elfutils-devel-0.170-5.el7.x86_64
elfutils-libs-0.170-4.el7.x86_64
elfutils-0.174-1.fc30.x86_64
elfutils-libelf-devel-0.170-4.el7.x86_64
[root@abc build]# yum install binutils-devel zlib-devel libcurl-devel
Loaded plugins: fastestmirror, langpacks, priorities
Loading mirror speeds from cached hostfile
* base: mirror.den1.denvercolo.net
* extras: ftp.osuosl.org
* updates: sjc.edge.kernel.org
Package binutils-devel-2.27-28.base.el7_5.1.x86_64 already installed and latest version
Package zlib-devel-1.2.7-17.el7.x86_64 already installed and latest version
Package libcurl-devel-7.29.0-46.el7.x86_64 already installed and latest version
Nothing to do
[root@abc build]#

**Comment by kernhanda** [comment]
Are you sure this is for ELL? The cmake output suggests you're building "kcov".

> linked by target "kcov" in directory /root/kcov-master/src
> 
> -- Configuring incomplete, errors occurred!
> See also "/root/kcov-master/build/CMakeFiles/CMakeOutput.log".
> See also "/root/kcov-master/build/CMakeFiles/CMakeError.log".
