### ISSUE TITLE
Keyword spotter detailed how-to guide please? 

### ISSUE THREAD

**Issue by repeeter** [Microsoft/ELL#183]
Hi, 
I'm quite a beginner, but very keen to try to get the ELL keyword spotter demo running on my MXChip board.  Any chance you could release something close to a step by step (or at least detailed guide, with all the tricks included .. )  ?
Thank you;

**Comment by lovettchris** [comment]
See [Keyword Spotting on MXCHIP](https://github.com/Microsoft/ELL/wiki/Keyword-Spotting-on-MXCHIP)

**Comment by clovett** [comment]
This is also now a new [Azure IoT devkit sample](https://github.com/IoTDevEnvExamples/DevKitKeywordSpotter/blob/master/README.md).
