### ISSUE TITLE
Q: support for IL2CPP and/or CoreRT

### ISSUE THREAD

**Issue by grahamehorner** [Microsoft/ELL#187]
Is there any plan to support the efforts of the CoreRT team AOT compiler output as cpp and/or native targeted executables ?

**Comment by lovettchris** [comment]
No.  But I see no reason why these things couldn't already work with the compiled neural network output from ELL:

![image](https://user-images.githubusercontent.com/18707114/50743801-f6067980-11d0-11e9-8feb-219273f66906.png)

and
![image](https://user-images.githubusercontent.com/18707114/50743831-4978c780-11d1-11e9-8aab-a4601c94b94b.png)

**Comment by grahamehorner** [comment]
I was thinking something more like 

neural network -> ELL -> C# -> CoreRT -> C++ ?
neural network -> ELL -> object + .h -> ?

as then ELL could build upon the CoreRT efforts and perhaps be deployed onto a platform that is not currently supported; but becomes a supported CoreRT platform ?

all just thinking aloud with ideas for the future; loving the fact ML/AI is running on the edge and the work you guys are doing :D  +1000

**Comment by clovett** [comment]
Well you might be looking for an ELL to C++ option, this would then give you more platform options (any platform that can compile that C++ code), but this is not currently supported.  But it is on our list of things to look into.

**Comment by grahamehorner** [comment]
@clover cool would love to contribute as when if you guys start this or believe the effort is worth the time

**Comment by lovettchris** [comment]
Sure thing, love to get some help.  In the meantime if you use IL2CPP or CoreRT to native code there it should already by possible to link the ELL generated object code into an existing native application.  I'd be happy to help get that working if you want to try something along those lines.
