### ISSUE TITLE
wrap.py: WrapException: <class 'buildtools.EllBuildToolsRunException'>

### ISSUE THREAD

**Issue by jnbli** [Microsoft/ELL#200]
I've put model.ell and categories.txt in a the same folder and run wrap.py, and I am getting an exception.

python3 /Users/jonathanli/Applications/squirrel-tracker/ELL/tools/wrap/wrap.py --model_file model.ell --language python --target host

copy "/Users/jonathanli/Applications/squirrel-tracker/ELL/CMake/OpenBLASSetup.cmake" "host/OpenBLASSetup.cmake"
compiling model...
/Users/jonathanli/Applications/squirrel-tracker/ELL/build/bin/compile -imap model.ell -cfn Predict -cmn model --bitcode --target host -od host --fuseLinearOps True --optimizeReorderDataNodes True --swig --blas true --optimize true
### WrapException: <class 'buildtools.EllBuildToolsRunException'>: /Users/jonathanli/Applications/squirrel-tracker/ELL/build/bin/compile -imap model.ell -cfn Predict -cmn model --bitcode --target host -od host --fuseLinearOps True --optimizeReorderDataNodes True --swig --blas true --optimize true

**Comment by lovettchris** [comment]
Can you run just the "compile" part of this command again with "--verbose" and report the output you see?
```
/Users/jonathanli/Applications/squirrel-tracker/ELL/build/bin/compile -imap model.ell -cfn Predict -cmn model --bitcode --target host -od host --fuseLinearOps True --optimizeReorderDataNodes True --swig --blas true --optimize true --verbose
```

**Comment by lovettchris** [comment]
Please try the latest bits.
