### ISSUE TITLE
Error during build ELL on ubuntu:  error: ‘outputLayout’ is not captured

### ISSUE THREAD

**Issue by jaehyunshinML** [microsoft/ELL#202]
Hi,

I am trying to set up ELL on ubuntu 18 by following the instruction.

After install requirements, try to make aftet cmake ..

The error came up :  error: ‘outputLayout’ is not captured 

ELL/libraries/nodes/include/BroadcastOperationNodes.h:515:58: error: ‘outputLayout’ is not captured
         const auto outputGlobalOffset = static_cast<int>(outputLayout.GetFirstEntryOffset())
Do you have any idea?

**Comment by lovettchris** [comment]
weird, static_cast is not a lambda, so there's nothing to capture.  But the previous line tries to do this "const auto&" to a return type of type "model::PortMemoryLayout" which also doesn't really make sense, so perhaps try replacing line 514 with this:
```cpp
model::PortMemoryLayout outputLayout = GetOutputMemoryLayout();
```

**Comment by lovettchris** [comment]
The latest bits have been tested on Ubuntu 18 and are building cleanly with gcc-8 and clang-8.
