### ISSUE TITLE
No module named 'darknet_to_ell'

### ISSUE THREAD

**Issue by malynda** [Microsoft/ELL#21]
I just built everything on my Ubuntu 16.04 box and was going to test the darknet tutorial, but alas! errors.

/build/tutorials/vision/gettingStarted$ python darknetDemo.py 
Traceback (most recent call last):
  File "darknetDemo.py", line 7, in <module>
    import darknet_to_ell
ModuleNotFoundError: No module named 'darknet_to_ell'

My guess is it doesn't know that darknet_to_ell is in /build/tools/importers/darknet
Not sure if this was supposed to be copied in the python build or if it needs to be directed to the correct folder.

**Comment by eulesv** [comment]
Did you use the rebuild.cmd? It uses a different configuration RelWithDebInfo, none of the scripts point to that one :(

**Comment by malynda** [comment]
Nope, just followed what the Python Language Bindings instructions on https://github.com/Microsoft/ELL/blob/master/interfaces/README.md said.

**Comment by jimaobian** [comment]
@malynda There is a typo in findEll.py :
`sys.path.append(buildDir + '/tools/importers/Darknet')`

Change `Darknet` to `darknet`

**Comment by malynda** [comment]
Thanks @jimaobian !  Have you already submitted a PR for that?
