### ISSUE TITLE
Square operation returns zero vector

### ISSUE THREAD

**Issue by mr-yamraj** [microsoft/ELL#223]
Hi I am trying to debug the file make_featurizer.py in tools/utilites/pythonlibs/audio/training

and when I am using the flag --power_spec it is returning zero values in the square node.
I checked the values of last_node before this operation and I has values greater than zero. But when I am performing square using the below code it is returning zero vector.
square_node = builder.AddUnaryOperationNode(
            ell_model, ell.nodes.PortElements(last_node.GetOutputPort("output")),
            ell.nodes.UnaryOperationType.square)

**Comment by mr-yamraj** [comment]
Other functions like sqrt, exp, tanh are working fine

**Comment by mr-yamraj** [comment]
In the same file the output that we get from the mel filterbank does not match with the output of the mel bank that I applied in python. I used https://github.com/jameslyons/python_speech_features/blob/master/python_speech_features/base.py#L149 as refrence to calculate the fbanks and the algorithm they have used to calculate the mel filter bank is correct.

**Comment by mr-yamraj** [comment]
Okay! found the bug for FFT will give a pull request but I am not finding the bug of the square (in my first comment)

**Comment by kernhanda** [comment]
This should be fixed in [v2.5.4](https://github.com/microsoft/ELL/releases/tag/v2.5.4)

**Comment by mr-yamraj** [comment]
Thanks! It works now.
