### ISSUE TITLE
Using LLVM opt tool with featurizer.bc gives error

### ISSUE THREAD

**Issue by nils-fl** [microsoft/ELL#237]
Hi,

I am trying to get my own model to the mxchip following the instructions from:
https://github.com/Microsoft/ELL/wiki/Keyword-Spotting-on-MXCHIP

When I try to use the llvm (6.0) opt tool under ubuntu, I get:

~/tutorial$ opt featurizer.bc -o featurizer.opt.bc -O3
Intrinsic has incorrect argument type!
void (i8*, i8*, i64, i1)* @llvm.memcpy.p0i8.p0i8.i64
Intrinsic has incorrect argument type!
void (i8*, i8*, i32, i1)* @llvm.memcpy.p0i8.p0i8.i32
opt: featurizer.bc: error: input module is broken!

I have no idea how to solve that. Is that an issue with the llvm version?

Best
Nils

**Comment by lovettchris** [comment]
The current windows build uses LLVMNativeWindowsLibs.x64.8.0.0-a
