### ISSUE TITLE
errors while running cmake --build . --config Release command

### ISSUE THREAD

**Issue by supurbnik9** [microsoft/ELL#243]
I got following errors while executing build command
cmake --build . --config Release

errors:
![Untitled](https://user-images.githubusercontent.com/57912826/74185834-6fdc2280-4c6f-11ea-998d-e528d9dae9bc.jpg)

**Comment by lovettchris** [comment]
This could indicate you are not building ell from a configured Python 3.6 environment.  See the [python setup steps](https://github.com/Microsoft/ELL/blob/master/INSTALL-Windows.md#using-ell-in-python).
