### ISSUE TITLE
Error Compiling ELL 

### ISSUE THREAD

**Issue by victorbutuza** [microsoft/ELL#244]
**C:\ELL\libraries\nodes\include\ConstantNode.h(271,123): error C2794: 'PortMemoryLayout': is not a member of any direct or indirect base class of '<Unknown>' (compiling source file C:\ELL\libraries\nodes\src\WinogradConvolutionNode.cpp) [C:\ELL\build\libraries\nodes\nodes.vcxproj]**

C:\ELL\libraries\nodes\src\WinogradConvolutionNode.cpp(1154): 
message : while compiling class template member function 'bool ell::nodes::WinogradConvolutionNode<float>::Refine(ell::model::ModelTransformer &) const' [C:\ELL\build\libraries\nodes\nodes.vcxproj]
C:\ELL\libraries\nodes\src\WinogradConvolutionNode.cpp(1530): message : see reference to class template instantiation 'ell::nodes::WinogradConvolutionNode<float>' being compiled [C:\ELL\build\libraries\nodes\nodes.vcxproj]

**C:\ELL\libraries\nodes\include\ConstantNode.h(263,123): error C2794: 'MemoryShape': is not a member of any direct or indirect base class of
 '<Unknown>' (compiling source file C:\\ELL\libraries\nodes\src\WinogradConvolutionNode.cpp) [C:\ELL\build\libraries\nodes\nodes.vcxproj]**

**Comment by lovettchris** [comment]
Indeed, something must have changed in the VC++ compiler, I'll push a fix.

**Comment by lovettchris** [comment]
Fix is pushed.
