### ISSUE TITLE
compile_darknetReference.cmd fails with cl.exe

### ISSUE THREAD

**Issue by eulesv** [Microsoft/ELL#26]
I'm trying to complete the tutorial to run off my Raspberry Pi and compile_darknetReference.cmd is failing on **swigging darknetReference.i to darknetReference_wrap.cpp**, if I don't specify anything it comes back with a file not found error; if I set a path folder containing cl.exe it comes up with
`error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\x86_amd64\\cl.exe' failed with exit status -1073741515`
I tried with different options for example x64_x86 and I still get the same result, any pointers or guidance?

Thanks
--Rp

**Comment by clovett** [comment]
compile_darknetReference.cmd  is gone, there is a new way to do that now if you sync to the latest bits.
