### ISSUE TITLE
sudo make Does Not Work on Ubuntu Linux 14.04 x86_64 

### ISSUE THREAD

**Issue by acs254** [Microsoft/ELL#4]
I can build just fine into `> ELL/build`, but upon running `sudo make`, I get a huge list of errors -- too long to post here. But it ends with:

```
make[2]: *** [libraries/utilities/CMakeFiles/utilities.dir/src/Archiver.cpp.o] Error 1
make[1]: *** [libraries/utilities/CMakeFiles/utilities.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by devilloser** [comment]
so do i

**Comment by lisaong** [comment]
Hi,

Thanks for bringing this up.

sudo make is not a supported build configuration for ELL at this time.  Is there a reason for needing to do `sudo make` instead of `make`?

Our make command does not install anything or require sudo privileges.

**Comment by DarrenRainey** [comment]
can you share a pastebin with your error log

**Comment by h4gen** [comment]
Hey! I have exactly the same issue but even without `sudo` I encounter the same problem. I tried to compile ELL in the CNTK docker container, provided by Microsoft, to build a consistent Toolchain in a transportable environment. I installed all dependencies in the [guide](https://github.com/Microsoft/ELL/blob/master/INSTALL-Ubuntu.md). 
The container also uses Ubuntu 14.04.

**Comment by lisaong** [comment]
Thanks for the details. Can you try a Ubuntu 16.04 container instead to see if it make a difference?

**Comment by h4gen** [comment]
Hey @lisaong. With a fresh Ubuntu 16.04 everything works now. Thanks!

**Comment by lisaong** [comment]
Great! Thanks for reporting back.

**Comment by pnvphuong** [comment]
There are some incompatibilities with Ubuntu14.
ELL requires gcc 5 or above, but CUDA 8 only supports gcc 4x for Ubuntu 14. Therefore, it's hard to install and build ELL on Ubuntu 14.
On the other hand, CUDA 8 supports gcc 5x for Ubuntu 16. Everything will be fine then

**Comment by lisaong** [comment]
Indeed, we are recommending Ubuntu 16.04 at minimum, unless there is a strong reason for using Ubuntu 14.
