### ISSUE TITLE
question: standalone, portable package selfcontained in a directory

### ISSUE THREAD

**Issue by dorvan** [Microsoft/ELL#49]
Is it possile evaluate to deploy ELL as standalone binary, a portable package selfcontained in a directory?

**Comment by clovett** [comment]
ELL needs to be installed as per our [README](https://github.com/Microsoft/ELL/blob/master/README.md), but once installed ELL can produce a compiled package in a directory that executes a given CNN model for a specified target platform.  This is what [compiling](https://github.com/Microsoft/ELL/blob/master/tutorials/vision/gettingStarted/compiling.md) is all about.  Think of ELL as a CNN compiler.
