### ISSUE TITLE
What is SWIG and do I need it. 

### ISSUE THREAD

**Issue by pquodling** [Microsoft/ELL#6]
CMake Warning at CMakeLists.txt:83 (message):
  SWIG not found, interfaces and projects that depend on them will not build
  properly.  They are not part of the default make targets, so can be
  skipped.  If you want to build interfaces (such as the Python bindings),
  follow the instructions in INSTALL-XXXXX.md file to install SWIG.  Then
  delete the CMakeCache.txt file from your build directory run the cmake
  command again.

-- Could NOT find SWIG (missing:  SWIG_EXECUTABLE SWIG_DIR) (Required is at least version "3.0.12")
CMake Warning at interfaces/python/CMakeLists.txt:9 (message):
  Couldn't find Python libraries 3.5 or later, _ELL_python target will not be
  build properly.  This is not a required component, so it can be skipped.

-- Could NOT find SWIG (missing:  SWIG_EXECUTABLE SWIG_DIR) (Required is at least version "3.0.12")
-- Creating wrappers for python
-- Could NOT find SWIG (missing:  SWIG_EXECUTABLE SWIG_DIR) (Required is at least version "3.0.12")
-- Creating wrappers for javascript
-- Found npm at /usr/local/bin/npm
-- Could NOT find SWIG (missing:  SWIG_EXECUTABLE SWIG_DIR) (Required is at least version "3.0.12")
-- Creating wrappers for xml
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/peter/Projects/ELL/build
[  0%] Built target documentation
[ 11%] Built target utilities
[ 12%] Built target math
[ 15%] Built

**Comment by eulesv** [comment]
Hi pquodling,

SWIG will allow to use ELL from other languages such as python, you can download SWIG from [http://www.swig.org/](http://www.swig.org/). If you need to build the interfaces (for example to run the tutorial), you'll need SWIG; you can follow the instructions on [https://github.com/Microsoft/ELL/tree/master/interfaces](https://github.com/Microsoft/ELL/tree/master/interfaces)

Hope it helps!
--Rp
