### ISSUE TITLE
rebuild.cmd should not rely on registry to detect VS 2017

### ISSUE THREAD

**Issue by eulesv** [Microsoft/ELL#60]
Rebuild.cmd does not identifies vs2017 properly on Win10 Creators update, according to this [link](https://blogs.msdn.microsoft.com/heaths/2016/09/15/changes-to-visual-studio-15-setup/) the detection mechanism changed for vs2017

**Comment by clovett** [comment]
Thanks for the pointer, I agree we should use "vswhere.exe" to handle VS 2017 setup.

**Comment by lovettchris** [comment]
Fixed now.
