### ISSUE TITLE
[Error] Build on Raspberry Pi 3 due to missing darknetReference.map file

### ISSUE THREAD

**Issue by jong1prk** [Microsoft/ELL#62]
I have build ELL on Ubuntu with the [compiling instruction](https://github.com/Microsoft/ELL/blob/master/tutorials/vision/gettingStarted/compiling-Pi3.md) of Pi3, following exactly the same with it.

It have succeeded just entering "make" command, 
but "make compiled_darknetReference_pi3" got me this message below. 

Environment was Ubuntu 16.04.

[ 17%] Built target utilities
[ 19%] Built target math
[ 25%] Built target data
[ 40%] Built target emitters
[ 42%] Built target evaluators
[ 48%] Built target functions
[ 61%] Built target model
[ 65%] Built target predictors
[ 78%] Built target nodes
[ 84%] Built target trainers
[ 96%] Built target common
[ 98%] Built target compile
make[3]: *** No rule to make target 'tutorials/vision/gettingStarted/darknetReference.map', needed by 'tutorials/vision/gettingStarted/compiled_darknetReference_pi3/darknetReference.bc'.  Stop.
CMakeFiles/Makefile2:3311: recipe for target 'tutorials/vision/gettingStarted/CMakeFiles/compiled_darknetReference_pi3.dir/all' failed
make[2]: *** [tutorials/vision/gettingStarted/CMakeFiles/compiled_darknetReference_pi3.dir/all] Error 2
CMakeFiles/Makefile2:3318: recipe for target 'tutorials/vision/gettingStarted/CMakeFiles/compiled_darknetReference_pi3.dir/rule' failed
make[1]: *** [tutorials/vision/gettingStarted/CMakeFiles/compiled_darknetReference_pi3.dir/rule] Error 2
Makefile:896: recipe for target 'compiled_darknetReference_pi3' failed
make: *** [compiled_darknetReference_pi3] Error 2

I have no idea how to solve this problem..

**Comment by lisaong** [comment]
Hi, please start with the steps in [darknet.md](https://github.com/Microsoft/ELL/blob/master/tutorials/vision/gettingStarted/darknet.md), which will run the model on your desktop and generate the .map file.
