### ISSUE TITLE
Windows 10 64 build errors ..

### ISSUE THREAD

**Issue by ack72tdp** [Microsoft/ELL#75]
Any ideas on what I missed ..? 

I had all installed properly ..
Full Anaconda
nuget
openBLAS
C:\Program Files (x86)\Microsoft Visual Studio\2017
and CMAKE

and all paths are set right .. 

(py36) c:\MSELL\ELL\build>cmake -G "Visual Studio 15 2017 Win64" -DPROCESSOR_HINT=haswell ..
CMake Error at CMakeLists.txt:7 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

-- Configuring incomplete, errors occurred!
See also "C:/MSELL/ELL/build/CMakeFiles/CMakeOutput.log".

(py36) c:\MSELL\ELL\build>cmake --build . --config Release
The system cannot find the file specified
CMake Error: Generator: execution of make failed. Make command was: "MSBuild.exe" "ALL_BUILD.vcxproj" "/p:Configuration=Release" "/p:VisualStudioVersion=15.0"

**Comment by ack72tdp** [comment]
output of C:/MSELL/ELL/build/CMakeFiles/CMakeOutput.log". just says ..  
The system is: Windows - 10.0.10586 - AMD64

**Comment by ack72tdp** [comment]
MSBuild appear to be in path

(py36) c:\MSELL\ELL\build>MSbuild
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

**Comment by ack72tdp** [comment]
never mind .. missed ... Desktop Development with C++

**Comment by y-vyrovoy** [comment]
so what was the solution?

**Comment by kernhanda** [comment]
@y-vyrovoy, looks like he forgot to select "Desktop Development with C++" when he was running the VS installer.

**Comment by Weiney** [comment]
I have the same problem today,to solve this
add ms path to the Environmental path
like  D:\Microsoft Visual Studio\MSBuild\15.0\Bin

**Comment by baluoteliz** [comment]
ye,i also encontered the same problem.
,the solution is rechoose the vs tools for your environment.
as below:
vc14 vs2015
vc15 vs 2017...
