### ISSUE TITLE
Performace Bench Mark

### ISSUE THREAD

**Issue by amitsrivastava78** [Microsoft/ELL#77]
Dear Supporter,
               We would like to know if you guys have done the performance bench mark with respect to tensorflow/tensorflow light, caffee/caffee2 or other such frameworks ? If so please provide the details about the performace bench mark data.

Regards
Amit

**Comment by lovettchris** [comment]
We do not, but we do publish times on the models we have published in [our gallery](https://microsoft.github.io/ELL/gallery/)
