### ISSUE TITLE
INSTALL-Mac.md cmake build fails... error: use of undeclared identifier 'CLOCK_REALTIME'

### ISSUE THREAD

**Issue by norbertfuhs** [Microsoft/ELL#85]
I tried to follow the steps provided by INSTALL-Mac.md to build ELL on my Mac with cmake but it stops at 23% with:

[ 23%] Building CXX object libraries/emitters/CMakeFiles/emitters.dir/src/IRRuntime.cpp.o
/Users/noby/Code/Python/ell-py-raspberry_pi3/ELL/libraries/emitters/src/IRRuntime.cpp:216:85: error: use of undeclared identifier 'CLOCK_REALTIME'
                auto callResult = function.Call(getTimeFunction, { function.Literal(CLOCK_REALTIME), timeStruct });
                                                                                    ^
1 error generated.
make[2]: *** [libraries/emitters/CMakeFiles/emitters.dir/src/IRRuntime.cpp.o] Error 1
make[1]: *** [libraries/emitters/CMakeFiles/emitters.dir/all] Error 2
make: *** [all] Error 2

Here is the whole output:

noby@Mac-mini ~/Code/Python/ell-py-raspberry_pi3/ELL/build (master) $ source activate py36
(py36) noby@Mac-mini ~/Code/Python/ell-py-raspberry_pi3/ELL/build (master) $ cmake ..
-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Blas libraries: /System/Library/Frameworks/Accelerate.framework
-- Blas linker flags:
-- Blas include directories:
-- Using BLAS include path: /System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers
-- Using BLAS library: /System/Library/Frameworks/Accelerate.framework
-- Using BLAS DLLs:
-- Found PythonInterp: /Users/noby/miniconda3/envs/py36/bin/python (found version "3.6.1")
-- Found PythonLibs: /Users/noby/miniconda3/envs/py36/lib/libpython3.6m.dylib (found version "3.6.1")
-- Found SWIG: /usr/local/bin/swig (found suitable version "3.0.12", minimum required is "3.0.12")
-- Creating wrappers for python
CMake Deprecation Warning at /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/UseSWIG.cmake:228 (message):
  SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
Call Stack (most recent call first):
  CMake/CommonInterfaces.cmake:159 (swig_add_module)
  CMake/CommonInterfaces.cmake:190 (generate_interface_module)
  interfaces/python/CMakeLists.txt:21 (generate_interface)

-- Creating wrappers for javascript
-- Found npm at /Users/noby/.nvm/versions/node/v8.4.0/bin/npm
-- Creating wrappers for xml
-- Using python found at: /Users/noby/miniconda3/envs/py36/bin/python
-- Using python libraries found at: /Users/noby/miniconda3/envs/py36/lib/libpython3.6m.dylib
-- Creating wrappers for python
CMake Deprecation Warning at /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/UseSWIG.cmake:228 (message):
  SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
Call Stack (most recent call first):
  CMake/CommonInterfaces.cmake:159 (swig_add_module)
  CMake/CommonInterfaces.cmake:237 (generate_interface_module)
  examples/emitted_interfaces/step/CMakeLists.txt:25 (generate_emitted_interface_module)

-- Generated target compiled_vgg16ImageNet_host
-- Generated target compiled_vgg16ImageNet_host_profile
-- Generated target compiled_vgg16ImageNet_pi3
-- Generated target compiled_vgg16ImageNet_pi3_profile
-- Generated target compiled_vgg16ImageNet_pi0
-- Generated target compiled_vgg16ImageNet_aarch64
-- Generated target compiled_darknetReference_host
-- Generated target compiled_darknetReference_host_profile
-- Generated target compiled_darknetReference_pi3
-- Generated target compiled_darknetReference_pi3_profile
-- Generated target compiled_darknetReference_pi0
-- Generated target compiled_darknetReference_aarch64
CMake Warning at CMakeLists.txt:134 (message):
  Doxygen processor not found

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/noby/Code/Python/ell-py-raspberry_pi3/ELL/build
(py36) noby@Mac-mini ~/Code/Python/ell-py-raspberry_pi3/ELL/build (master) $ make
Scanning dependencies of target documentation
[  0%] Built target documentation
Scanning dependencies of target utilities
[  0%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/Archiver.cpp.o
[  1%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/CommandLineParser.cpp.o
[  1%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/CompressedIntegerList.cpp.o
[  2%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/ConformingVector.cpp.o
[  2%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/CStringParser.cpp.o
[  2%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/Files.cpp.o
[  3%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/Format.cpp.o
[  3%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/IArchivable.cpp.o
[  3%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/IndentedTextWriter.cpp.o
[  4%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/IntegerList.cpp.o
[  4%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/IntegerStack.cpp.o
[  6%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/JsonArchiver.cpp.o
[  6%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/ObjectArchive.cpp.o
[  6%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/ObjectArchiver.cpp.o
[  7%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/OutputStreamImpostor.cpp.o
[  7%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/PPMImageParser.cpp.o
[  7%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/RandomEngines.cpp.o
[  8%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/Tokenizer.cpp.o
[  8%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/TypeName.cpp.o
[  9%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/UniqueId.cpp.o
[  9%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/Variant.cpp.o
[  9%] Building CXX object libraries/utilities/CMakeFiles/utilities.dir/src/XmlArchiver.cpp.o
[ 11%] Linking CXX static library libutilities.a
[ 11%] Built target utilities
Scanning dependencies of target math
[ 12%] Building CXX object libraries/math/CMakeFiles/math.dir/src/BlasWrapper.cpp.o
[ 12%] Linking CXX static library libmath.a
[ 12%] Built target math
Scanning dependencies of target data
[ 12%] Building CXX object libraries/data/CMakeFiles/data.dir/src/Dataset.cpp.o
[ 12%] Building CXX object libraries/data/CMakeFiles/data.dir/src/DataVector.cpp.o
[ 13%] Building CXX object libraries/data/CMakeFiles/data.dir/src/DataVectorOperations.cpp.o
[ 13%] Building CXX object libraries/data/CMakeFiles/data.dir/src/GeneralizedSparseParsingIterator.cpp.o
[ 14%] Building CXX object libraries/data/CMakeFiles/data.dir/src/SequentialLineIterator.cpp.o
[ 14%] Building CXX object libraries/data/CMakeFiles/data.dir/src/TextLine.cpp.o
[ 14%] Building CXX object libraries/data/CMakeFiles/data.dir/src/WeightLabel.cpp.o
[ 16%] Linking CXX static library libdata.a
[ 16%] Built target data
Scanning dependencies of target emitters
[ 17%] Building CXX object libraries/emitters/CMakeFiles/emitters.dir/src/EmitterTypes.cpp.o
[ 17%] Building CXX object libraries/emitters/CMakeFiles/emitters.dir/src/IRAssemblyWriter.cpp.o
[ 17%] Building CXX object libraries/emitters/CMakeFiles/emitters.dir/src/IRBlockRegion.cpp.o
[ 18%] Building CXX object libraries/emitters/CMakeFiles/emitters.dir/src/IRDiagnosticHandler.cpp.o
[ 18%] Building CXX object libraries/emitters/CMakeFiles/emitters.dir/src/IREmitter.cpp.o
[ 18%] Building CXX object libraries/emitters/CMakeFiles/emitters.dir/src/IRExecutionEngine.cpp.o
[ 19%] Building CXX object libraries/emitters/CMakeFiles/emitters.dir/src/IRFunctionEmitter.cpp.o
[ 19%] Building CXX object libraries/emitters/CMakeFiles/emitters.dir/src/IRHeaderWriter.cpp.o
[ 20%] Building CXX object libraries/emitters/CMakeFiles/emitters.dir/src/IRIfEmitter.cpp.o
[ 20%] Building CXX object libraries/emitters/CMakeFiles/emitters.dir/src/IRLoader.cpp.o
[ 20%] Building CXX object libraries/emitters/CMakeFiles/emitters.dir/src/IRLoopEmitter.cpp.o
[ 22%] Building CXX object libraries/emitters/CMakeFiles/emitters.dir/src/IRMetadata.cpp.o
[ 22%] Building CXX object libraries/emitters/CMakeFiles/emitters.dir/src/IRModuleEmitter.cpp.o
[ 23%] Building CXX object libraries/emitters/CMakeFiles/emitters.dir/src/IROptimizer.cpp.o
[ 23%] Building CXX object libraries/emitters/CMakeFiles/emitters.dir/src/IRRuntime.cpp.o
/Users/noby/Code/Python/ell-py-raspberry_pi3/ELL/libraries/emitters/src/IRRuntime.cpp:216:85: error: use of undeclared identifier 'CLOCK_REALTIME'
                auto callResult = function.Call(getTimeFunction, { function.Literal(CLOCK_REALTIME), timeStruct });
                                                                                    ^
1 error generated.
make[2]: *** [libraries/emitters/CMakeFiles/emitters.dir/src/IRRuntime.cpp.o] Error 1
make[1]: *** [libraries/emitters/CMakeFiles/emitters.dir/all] Error 2
make: *** [all] Error 2

**Comment by lovettchris** [comment]
Weird, I know for sure folks have built ELL no problems on OSX, but I see there is some discussion about this on [stackoverflow](https://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x).  I suppose you could try defining CLOCK_REALTIME to 0 like we do on windows.
