### ISSUE TITLE
ELL porting on Android

### ISSUE THREAD

**Issue by dayanandasiet** [Microsoft/ELL#96]
Dear Team,

am happy to use ELL on x86 machine, but looking forward to use in Android phone. Is any plan to bring ELL solution on andoird or any suggestion how i can bring if possible.

@ lisaong help on this

**Comment by irjudson** [comment]
+1

**Comment by lovettchris** [comment]
ELL is a "cross-compiler" so you should be able to use ELL to compile a model targeting your Android device, this will produce object code that you can then link into your Android app using C++ to call the "predict" method that ELL has compiled into that object code.  The only trick is making sure your wrap.py target parameters match the target android device you are running on.  Usually armv7 I would think.  You will be using these `~/ELL/build/bin/compile` options:
```
Target device options
        --target (-t) [host]              target name  {host | pi0 | pi3 | orangepi0 | pi3_64 | mac | linux | windows | ios | aarch64 | custom}
        --numBits (-b) [0]                Number of bits for target [0 == auto]
        --cpu (-cpu) []                   The CPU target for generating code
        --triple []                       The triple describing the target architecture
        --datalayout []                   The string describing the target data layout
        --features []                     A string describing target-specific features to enable or disable (these are LLVM attributes, in the format the llc -mattr option uses)
```
