### ISSUE TITLE
Traning CNN in ELL

### ISSUE THREAD

**Issue by Ppinjari** [Microsoft/ELL#99]
Does ELL support training a CNN from scratch with help of labelled dataset? Does anyone have written any python script to train CNN in ELL?

**Comment by clovett** [comment]
No, ELL is not a CNN training system, it is a compiler for CNN's (and other ML algorithms) that optimizes the execution of a pre-trained model on a given target platform with a focus on embedded platforms, like Raspberry Pi.  ELL currently supports importing trained models from [CNTK ](https://docs.microsoft.com/en-us/cognitive-toolkit/)and [darknet](https://pjreddie.com/darknet/).

**Comment by Ppinjari** [comment]
If it doesn't support training of neural network, then what is the use case of trainers (SGD, SDCA, etc) that ELL is supporting. (Trainers are defined in libraries/trainers/). Will ELL support training of CNN in near future?

**Comment by lovettchris** [comment]
The trainers in the libraries folder are only there because they are unique to ELL and do not exist elsewhere.  There is no plan for ELL to duplicate CNTK or tensorflow training.  ELL is focused on optimizing the inference side for running trained models on embedded hardware.
